// serdesblock.v

// Generated using ACDS version 20.4 72

`timescale 1 ps / 1 ps
module serdesblock (
		input  wire [127:0] tx_in,        //        tx_in.export
		output wire [15:0]  tx_out,       //       tx_out.export
		output wire         tx_coreclock, // tx_coreclock.export
		input  wire         tx_inclock,   //      inclock.export
		input  wire         pll_areset,   //   pll_areset.export
		output wire         tx_locked     //   pll_locked.export
	);

	serdesblock_altera_lvds_1950_qebrfpq lvds_0 (
		.tx_in        (tx_in),        //   input,  width = 128,        tx_in.export
		.tx_out       (tx_out),       //  output,   width = 16,       tx_out.export
		.tx_coreclock (tx_coreclock), //  output,    width = 1, tx_coreclock.export
		.tx_inclock   (tx_inclock),   //   input,    width = 1,      inclock.export
		.pll_areset   (pll_areset),   //   input,    width = 1,   pll_areset.export
		.tx_locked    (tx_locked)     //  output,    width = 1,   pll_locked.export
	);

endmodule
