# This file is auto-generated.
# It is used by make_qii_design.tcl and make_sim_design.tcl, and
# is not intended to be executed directly.

set ip_params(SYS_INFO_DEVICE_FAMILY) "Cyclone 10 GX"
set ip_params(SYS_INFO_DEVICE) "10CX220YF780E5G"
set ip_params(SYS_INFO_UNIQUE_ID) "serdesblock_lvds_0"
set ip_params(SYS_INFO_DEVICE_SPEEDGRADE) "5"
set ip_params(SYS_INFO_DEVICE_DIE_REVISIONS) ""
set ip_params(MODE) "TX"
set ip_params(DUPLEX_MODE) "RX_Non-DPA"
set ip_params(USE_EXTERNAL_PLL) "false"
set ip_params(USE_CLOCK_PIN) "false"
set ip_params(NUM_CHANNELS) "1"
set ip_params(NUM_CHANNELS_TX) "1"
set ip_params(J_FACTOR) "8"
set ip_params(DATA_RATE) "1280.0"
set ip_params(INCLOCK_FREQUENCY) "40.0"
set ip_params(REFCLK_FROM_CORE) "false"
set ip_params(ENABLE_MIGRATABLE_PORT_MAPPINGS) "false"
set ip_params(ENABLE_UFI_COUNTER_SIM) "0"
set ip_params(REAL_MODE) "TX"
set ip_params(ACTUAL_INCLOCK_FREQUENCY) "40.0"
set ip_params(PORT_MAP_FILE_NAME) "port_map_tx.csv"
set ip_params(RX_USE_BITSLIP) "false"
set ip_params(RX_INCLOCK_PHASE_SHIFT) "0"
set ip_params(RX_RCCS_VAL) "0.0"
set ip_params(RX_BITSLIP_USE_RESET) "false"
set ip_params(RX_BITSLIP_ASSERT_MAX) "false"
set ip_params(RX_DPA_USE_RESET) "false"
set ip_params(RX_DPA_LOSE_LOCK_ON_ONE_CHANGE) "false"
set ip_params(RX_DPA_ALIGN_TO_RISING_EDGE_ONLY) "false"
set ip_params(RX_DPA_USE_HOLD) "false"
set ip_params(ENABLE_DIV_RECONFIG) "false"
set ip_params(ENABLE_CPA_RECONFIG) "false"
set ip_params(RX_FIFO_USE_RESET) "false"
set ip_params(RX_CDR_SIMULATION_PPM_DRIFT) "0"
set ip_params(RX_INCLOCK_PHASE_SHIFT_ACTUAL) "0"
set ip_params(RX_DPA_LOCKED_USED) "false"
set ip_params(RX_BITSLIP_ROLLOVER) "8"
set ip_params(TX_USE_OUTCLOCK) "true"
set ip_params(TX_OUTCLOCK_DIVISION) "2"
set ip_params(TX_OUTCLOCK_PHASE_SHIFT) "0"
set ip_params(TX_EXPORT_CORECLOCK) "true"
set ip_params(TX_REGISTER_CLOCK) "tx_coreclock"
set ip_params(TX_OUTCLOCK_PHASE_SHIFT_ACTUAL) "0"
set ip_params(TX_OUTCLOCK_NON_STD_PHASE_SHIFT) "false"
set ip_params(PLL_CORECLOCK_RESOURCE) "Periphery"
set ip_params(PLL_USE_RESET) "true"
set ip_params(GENERATE_SDC_FILE) "true"
set ip_params(CPA_ENABLED) "false"
set ip_params(CPA_ENABLED_SHADOW) "false"
set ip_params(DUPLEX_ENABLED) "false"
set ip_params(PLL_EXPORT_LOCK) "true"
set ip_params(pll_fclk_frequency) "1280.000000 MHz"
set ip_params(pll_fclk_phase_shift) "391 ps"
set ip_params(pll_sclk_frequency) "160.000000 MHz"
set ip_params(pll_sclk_phase_shift) "0 ps"
set ip_params(pll_loaden_frequency) "160.000000 MHz"
set ip_params(pll_loaden_phase_shift) "5467 ps"
set ip_params(pll_loaden_duty_cycle) "13"
set ip_params(pll_tx_outclock_frequency) "640.000000 MHz"
set ip_params(pll_tx_outclock_phase_shift) "391 ps"
set ip_params(pll_tx_outclock_fclk_frequency) "1280.000000 MHz"
set ip_params(pll_tx_outclock_fclk_phase_shift) "391 ps"
set ip_params(pll_tx_outclock_loaden_frequency) "160.000000 MHz"
set ip_params(pll_tx_outclock_loaden_phase_shift) "5467 ps"
set ip_params(pll_dprio_clk_frequency) "40.000000 MHz"
set ip_params(pll_vco_frequency) "1280.000000 MHz"
set ip_params(pll_inclock_frequency) "40.0 MHz"
set ip_params(PLL_SPEED_GRADE) "5"
set ip_params(DERIVED_CPA_ENABLED) "false"
set ip_params(GUI_CLOCK_PARAM_NAMES) ""
set ip_params(GUI_CLOCK_PARAM_VALUES) ""
set ip_params(mapped_sys_info_device_family) "Cyclone 10 GX"
set ip_params(mapped_sys_info_device) "10CX220YF780E5G"
set ip_params(mapped_sys_info_device_speedgrade) "5"
set ip_params(mapped_reference_clock_frequency) "40.0 MHz"
set ip_params(mapped_vco_frequency) "1280.0 MHz"
set ip_params(mapped_external_pll_mode) "false"
set ip_params(gui_enable_advanced_mode) "0"
set ip_params(gui_compensation_mode) "direct"
set ip_params(gui_number_of_pll_output_clocks) "0"
set ip_params(gui_desired_outclk_frequency_0) "1280.0"
set ip_params(gui_actual_outclk_frequency_0) "1280.000000"
set ip_params(hp_actual_outclk_frequency_0) "1280.0"
set ip_params(gui_outclk_phase_shift_unit_0) "0"
set ip_params(gui_outclk_desired_phase_shift_0) "391.0"
set ip_params(gui_outclk_actual_phase_shift_ps_0) "391"
set ip_params(gui_outclk_actual_phase_shift_deg_0) "180.2"
set ip_params(hp_outclk_actual_phase_shift_0) "390.625"
set ip_params(gui_desired_outclk_duty_cycle_0) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_0) "50"
set ip_params(hp_actual_outclk_duty_cycle_0) "50.0"
set ip_params(gui_desired_outclk_frequency_1) "160.0"
set ip_params(gui_actual_outclk_frequency_1) "160.000000"
set ip_params(hp_actual_outclk_frequency_1) "160.0"
set ip_params(gui_outclk_phase_shift_unit_1) "0"
set ip_params(gui_outclk_desired_phase_shift_1) "5467.0"
set ip_params(gui_outclk_actual_phase_shift_ps_1) "5467"
set ip_params(gui_outclk_actual_phase_shift_deg_1) "314.9"
set ip_params(hp_outclk_actual_phase_shift_1) "5468.75"
set ip_params(gui_desired_outclk_duty_cycle_1) "13.0"
set ip_params(gui_actual_outclk_duty_cycle_1) "13"
set ip_params(hp_actual_outclk_duty_cycle_1) "12.5"
set ip_params(gui_desired_outclk_frequency_2) "160.0"
set ip_params(gui_actual_outclk_frequency_2) "160.000000"
set ip_params(hp_actual_outclk_frequency_2) "160.0"
set ip_params(gui_outclk_phase_shift_unit_2) "0"
set ip_params(gui_outclk_desired_phase_shift_2) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_2) "0"
set ip_params(gui_outclk_actual_phase_shift_deg_2) "0.0"
set ip_params(hp_outclk_actual_phase_shift_2) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_2) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_2) "50"
set ip_params(hp_actual_outclk_duty_cycle_2) "50.0"
set ip_params(gui_desired_outclk_frequency_3) "0.0"
set ip_params(gui_actual_outclk_frequency_3) "N/A"
set ip_params(hp_actual_outclk_frequency_3) "1280.0"
set ip_params(gui_outclk_phase_shift_unit_3) "0"
set ip_params(gui_outclk_desired_phase_shift_3) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_3) "N/A"
set ip_params(gui_outclk_actual_phase_shift_deg_3) "N/A"
set ip_params(hp_outclk_actual_phase_shift_3) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_3) "0.0"
set ip_params(gui_actual_outclk_duty_cycle_3) "N/A"
set ip_params(hp_actual_outclk_duty_cycle_3) "50.0"
set ip_params(gui_desired_outclk_frequency_4) "0.0"
set ip_params(gui_actual_outclk_frequency_4) "N/A"
set ip_params(hp_actual_outclk_frequency_4) "1280.0"
set ip_params(gui_outclk_phase_shift_unit_4) "0"
set ip_params(gui_outclk_desired_phase_shift_4) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_4) "N/A"
set ip_params(gui_outclk_actual_phase_shift_deg_4) "N/A"
set ip_params(hp_outclk_actual_phase_shift_4) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_4) "0.0"
set ip_params(gui_actual_outclk_duty_cycle_4) "N/A"
set ip_params(hp_actual_outclk_duty_cycle_4) "50.0"
set ip_params(gui_desired_outclk_frequency_5) "100.0"
set ip_params(gui_actual_outclk_frequency_5) "100.0"
set ip_params(hp_actual_outclk_frequency_5) "100.0"
set ip_params(gui_outclk_phase_shift_unit_5) "0"
set ip_params(gui_outclk_desired_phase_shift_5) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_5) "0.0"
set ip_params(gui_outclk_actual_phase_shift_deg_5) "0.0"
set ip_params(hp_outclk_actual_phase_shift_5) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_5) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_5) "50.0"
set ip_params(hp_actual_outclk_duty_cycle_5) "50.0"
set ip_params(gui_desired_outclk_frequency_6) "100.0"
set ip_params(gui_actual_outclk_frequency_6) "100.0"
set ip_params(hp_actual_outclk_frequency_6) "100.0"
set ip_params(gui_outclk_phase_shift_unit_6) "0"
set ip_params(gui_outclk_desired_phase_shift_6) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_6) "0.0"
set ip_params(gui_outclk_actual_phase_shift_deg_6) "0.0"
set ip_params(hp_outclk_actual_phase_shift_6) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_6) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_6) "50.0"
set ip_params(hp_actual_outclk_duty_cycle_6) "50.0"
set ip_params(gui_desired_outclk_frequency_7) "100.0"
set ip_params(gui_actual_outclk_frequency_7) "100.0"
set ip_params(hp_actual_outclk_frequency_7) "100.0"
set ip_params(gui_outclk_phase_shift_unit_7) "0"
set ip_params(gui_outclk_desired_phase_shift_7) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_7) "0.0"
set ip_params(gui_outclk_actual_phase_shift_deg_7) "0.0"
set ip_params(hp_outclk_actual_phase_shift_7) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_7) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_7) "50.0"
set ip_params(hp_actual_outclk_duty_cycle_7) "50.0"
set ip_params(gui_desired_outclk_frequency_8) "100.0"
set ip_params(gui_actual_outclk_frequency_8) "100.0"
set ip_params(hp_actual_outclk_frequency_8) "100.0"
set ip_params(gui_outclk_phase_shift_unit_8) "0"
set ip_params(gui_outclk_desired_phase_shift_8) "0.0"
set ip_params(gui_outclk_actual_phase_shift_ps_8) "0.0"
set ip_params(gui_outclk_actual_phase_shift_deg_8) "0.0"
set ip_params(hp_outclk_actual_phase_shift_8) "0.0"
set ip_params(gui_desired_outclk_duty_cycle_8) "50.0"
set ip_params(gui_actual_outclk_duty_cycle_8) "50.0"
set ip_params(hp_actual_outclk_duty_cycle_8) "50.0"
set device_family  "Cyclone 10 GX"
set pro_edition  1
set ed_params(ALTERA_LVDS_NAME)           "lvds_0_example_design"
set ed_params(DEFAULT_DEVICE)      "10CX220YF780E5G"
set ed_params(SYNTH_QSYS_NAME)     "ed_synth"
set ed_params(SYNTH_DPS_QSYS_NAME) "ed_synth_dps"
set ed_params(SYNTH_TX_RX_QSYS_NAME) "ed_synth_tx_rx"
set ed_params(SIM_QSYS_NAME)       "ed_sim"
set ed_params(TMP_SYNTH_QSYS_PATH) "C:/Users/47859205/AppData/Local/Temp/alt8786_1200151449736112740.dir/0002_lvds_0_gen/ed_synth.qsys"
set ed_params(TMP_SIM_QSYS_PATH)   "C:/Users/47859205/AppData/Local/Temp/alt8786_1200151449736112740.dir/0002_lvds_0_gen/ed_sim.qsys"
set ed_params(TMP_DPS_QSYS_PATH)   "C:/Users/47859205/AppData/Local/Temp/alt8786_1200151449736112740.dir/0002_lvds_0_gen/ed_synth_dps.qsys"
set ed_params(TMP_TX_RX_QSYS_PATH)   "C:/Users/47859205/AppData/Local/Temp/alt8786_1200151449736112740.dir/0002_lvds_0_gen/ed_synth_tx_rx.qsys"
lappend ed_params(EXTRA_COPY_FILES)   "qsys_interface_bridge"
